### ISSUE TITLE
Online demo with jquery-console

### ISSUE THREAD

**Issue by paf31** [Thimoteus/SandScript#1]
I just think this would make a really nice demo 😄 I'd be happy to help.

**Comment by Thimoteus** [comment]
:+1: I think I'll probably have to rewrite this from scratch since I haven't touched it since compiler version 0.7 or so.

Do you know of any purescript projects already using jquery console? I tried searching but didn't get any results.

**Comment by paf31** [comment]
🎆 This is great!

**Comment by paf31** [comment]
Do you mind if we add this to the PureScript.org projects page?

**Comment by Thimoteus** [comment]
That'd be awesome!
